// Generated by gencpp from file ouster_ros/GetConfig.msg
// DO NOT EDIT!


#ifndef OUSTER_ROS_MESSAGE_GETCONFIG_H
#define OUSTER_ROS_MESSAGE_GETCONFIG_H

#include <ros/service_traits.h>


#include <ouster_ros/GetConfigRequest.h>
#include <ouster_ros/GetConfigResponse.h>


namespace ouster_ros
{

struct GetConfig
{

typedef GetConfigRequest Request;
typedef GetConfigResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct GetConfig
} // namespace ouster_ros


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::ouster_ros::GetConfig > {
  static const char* value()
  {
    return "b3532af339db184b4a6a974d00ee4fe6";
  }

  static const char* value(const ::ouster_ros::GetConfig&) { return value(); }
};

template<>
struct DataType< ::ouster_ros::GetConfig > {
  static const char* value()
  {
    return "ouster_ros/GetConfig";
  }

  static const char* value(const ::ouster_ros::GetConfig&) { return value(); }
};


// service_traits::MD5Sum< ::ouster_ros::GetConfigRequest> should match
// service_traits::MD5Sum< ::ouster_ros::GetConfig >
template<>
struct MD5Sum< ::ouster_ros::GetConfigRequest>
{
  static const char* value()
  {
    return MD5Sum< ::ouster_ros::GetConfig >::value();
  }
  static const char* value(const ::ouster_ros::GetConfigRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::ouster_ros::GetConfigRequest> should match
// service_traits::DataType< ::ouster_ros::GetConfig >
template<>
struct DataType< ::ouster_ros::GetConfigRequest>
{
  static const char* value()
  {
    return DataType< ::ouster_ros::GetConfig >::value();
  }
  static const char* value(const ::ouster_ros::GetConfigRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::ouster_ros::GetConfigResponse> should match
// service_traits::MD5Sum< ::ouster_ros::GetConfig >
template<>
struct MD5Sum< ::ouster_ros::GetConfigResponse>
{
  static const char* value()
  {
    return MD5Sum< ::ouster_ros::GetConfig >::value();
  }
  static const char* value(const ::ouster_ros::GetConfigResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::ouster_ros::GetConfigResponse> should match
// service_traits::DataType< ::ouster_ros::GetConfig >
template<>
struct DataType< ::ouster_ros::GetConfigResponse>
{
  static const char* value()
  {
    return DataType< ::ouster_ros::GetConfig >::value();
  }
  static const char* value(const ::ouster_ros::GetConfigResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // OUSTER_ROS_MESSAGE_GETCONFIG_H
