// Generated by gencpp from file ouster_ros/SetConfig.msg
// DO NOT EDIT!


#ifndef OUSTER_ROS_MESSAGE_SETCONFIG_H
#define OUSTER_ROS_MESSAGE_SETCONFIG_H

#include <ros/service_traits.h>


#include <ouster_ros/SetConfigRequest.h>
#include <ouster_ros/SetConfigResponse.h>


namespace ouster_ros
{

struct SetConfig
{

typedef SetConfigRequest Request;
typedef SetConfigResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct SetConfig
} // namespace ouster_ros


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::ouster_ros::SetConfig > {
  static const char* value()
  {
    return "7c21f4ef724c955b8242aed00884d81a";
  }

  static const char* value(const ::ouster_ros::SetConfig&) { return value(); }
};

template<>
struct DataType< ::ouster_ros::SetConfig > {
  static const char* value()
  {
    return "ouster_ros/SetConfig";
  }

  static const char* value(const ::ouster_ros::SetConfig&) { return value(); }
};


// service_traits::MD5Sum< ::ouster_ros::SetConfigRequest> should match
// service_traits::MD5Sum< ::ouster_ros::SetConfig >
template<>
struct MD5Sum< ::ouster_ros::SetConfigRequest>
{
  static const char* value()
  {
    return MD5Sum< ::ouster_ros::SetConfig >::value();
  }
  static const char* value(const ::ouster_ros::SetConfigRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::ouster_ros::SetConfigRequest> should match
// service_traits::DataType< ::ouster_ros::SetConfig >
template<>
struct DataType< ::ouster_ros::SetConfigRequest>
{
  static const char* value()
  {
    return DataType< ::ouster_ros::SetConfig >::value();
  }
  static const char* value(const ::ouster_ros::SetConfigRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::ouster_ros::SetConfigResponse> should match
// service_traits::MD5Sum< ::ouster_ros::SetConfig >
template<>
struct MD5Sum< ::ouster_ros::SetConfigResponse>
{
  static const char* value()
  {
    return MD5Sum< ::ouster_ros::SetConfig >::value();
  }
  static const char* value(const ::ouster_ros::SetConfigResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::ouster_ros::SetConfigResponse> should match
// service_traits::DataType< ::ouster_ros::SetConfig >
template<>
struct DataType< ::ouster_ros::SetConfigResponse>
{
  static const char* value()
  {
    return DataType< ::ouster_ros::SetConfig >::value();
  }
  static const char* value(const ::ouster_ros::SetConfigResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // OUSTER_ROS_MESSAGE_SETCONFIG_H
