(cl:defpackage ouster_ros-srv
  (:use )
  (:export
   "GETCONFIG"
   "<GETCONFIG-REQUEST>"
   "GETCONFIG-REQUEST"
   "<GETCONFIG-RESPONSE>"
   "GETCONFIG-RESPONSE"
   "GETMETADATA"
   "<GETMETADATA-REQUEST>"
   "GETMETADATA-REQUEST"
   "<GETMETADATA-RESPONSE>"
   "GETMETADATA-RESPONSE"
   "SETCONFIG"
   "<SETCONFIG-REQUEST>"
   "SETCONFIG-REQUEST"
   "<SETCONFIG-RESPONSE>"
   "SETCONFIG-RESPONSE"
  ))

