#!/usr/bin/env python

import robot_upstart
import os

j = robot_upstart.Job(name="ros", interface=os.environ.get('ROBOT_NETWORK'), workspace_setup=os.environ.get('ROBOT_SETUP'))

# Stuff to launch on system startup.
j.add(package="husky_base", glob="launch/*")
j.add(package="husky_bringup", glob="launch/*")

j.install()
